# This is a basic workflow to help you get started with Actions

name: Build Emacs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout emacs
        uses: actions/checkout@v3
        with:
          repository: emacs-mirror/emacs
          ref: 'master'
          path: 'emacs'

      # Remove the preinstalled packages to reduce unwanted side-effects
      - name: Remove preinstalled brew packages
        run: brew remove --force --ignore-dependencies $(brew list --formula)

      - name: Install brew packages
        run: brew bundle --file Brewfile

      - name: Start dbus
        run: brew services start dbus

      - name: Run autogen
        run: ./autogen.sh
        working-directory: ./emacs

      - name: Run configure
        run: ./configure --with-native-compilation --with-json --with-mailutils --with-xwidgets --with-imagemagick
        working-directory: ./emacs

      - name: Run make
        run: make -j $(nproc)
        working-directory: ./emacs

      - name: Run make install
        run: make install
        working-directory: ./emacs

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        if: github.ref == 'refs/heads/main'
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          bodyFile: './emacs/nextstep/Emacs.app'
